# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookStore_LuizVasconcellos' do
  use_frameworks!

  pod 'Alamofire', '~> 5.4'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Swinject'
  pod 'SwinjectAutoregistration'
  pod 'SwinjectStoryboard'

end
